// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.nasa.hackson.nasachatbot.web.controller;

import com.nasa.hackson.nasachatbot.domain.MsgElement;
import com.nasa.hackson.nasachatbot.domain.PayLoad;
import com.nasa.hackson.nasachatbot.web.controller.PayLoadController;
import java.io.UnsupportedEncodingException;
import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.util.UriUtils;
import org.springframework.web.util.WebUtils;

privileged aspect PayLoadController_Roo_Controller {
    
    @RequestMapping(method = RequestMethod.POST, produces = "text/html")
    public String PayLoadController.create(@Valid PayLoad payLoad, BindingResult bindingResult, Model uiModel, HttpServletRequest httpServletRequest) {
        if (bindingResult.hasErrors()) {
            populateEditForm(uiModel, payLoad);
            return "payloads/create";
        }
        uiModel.asMap().clear();
        payLoad.persist();
        return "redirect:/payloads/" + encodeUrlPathSegment(payLoad.getId().toString(), httpServletRequest);
    }
    
    @RequestMapping(params = "form", produces = "text/html")
    public String PayLoadController.createForm(Model uiModel) {
        populateEditForm(uiModel, new PayLoad());
        return "payloads/create";
    }
    
    @RequestMapping(value = "/{id}", produces = "text/html")
    public String PayLoadController.show(@PathVariable("id") Long id, Model uiModel) {
        uiModel.addAttribute("payload", PayLoad.findPayLoad(id));
        uiModel.addAttribute("itemId", id);
        return "payloads/show";
    }
    
    @RequestMapping(produces = "text/html")
    public String PayLoadController.list(@RequestParam(value = "page", required = false) Integer page, @RequestParam(value = "size", required = false) Integer size, @RequestParam(value = "sortFieldName", required = false) String sortFieldName, @RequestParam(value = "sortOrder", required = false) String sortOrder, Model uiModel) {
        if (page != null || size != null) {
            int sizeNo = size == null ? 10 : size.intValue();
            final int firstResult = page == null ? 0 : (page.intValue() - 1) * sizeNo;
            uiModel.addAttribute("payloads", PayLoad.findPayLoadEntries(firstResult, sizeNo, sortFieldName, sortOrder));
            float nrOfPages = (float) PayLoad.countPayLoads() / sizeNo;
            uiModel.addAttribute("maxPages", (int) ((nrOfPages > (int) nrOfPages || nrOfPages == 0.0) ? nrOfPages + 1 : nrOfPages));
        } else {
            uiModel.addAttribute("payloads", PayLoad.findAllPayLoads(sortFieldName, sortOrder));
        }
        return "payloads/list";
    }
    
    @RequestMapping(method = RequestMethod.PUT, produces = "text/html")
    public String PayLoadController.update(@Valid PayLoad payLoad, BindingResult bindingResult, Model uiModel, HttpServletRequest httpServletRequest) {
        if (bindingResult.hasErrors()) {
            populateEditForm(uiModel, payLoad);
            return "payloads/update";
        }
        uiModel.asMap().clear();
        payLoad.merge();
        return "redirect:/payloads/" + encodeUrlPathSegment(payLoad.getId().toString(), httpServletRequest);
    }
    
    @RequestMapping(value = "/{id}", params = "form", produces = "text/html")
    public String PayLoadController.updateForm(@PathVariable("id") Long id, Model uiModel) {
        populateEditForm(uiModel, PayLoad.findPayLoad(id));
        return "payloads/update";
    }
    
    @RequestMapping(value = "/{id}", method = RequestMethod.DELETE, produces = "text/html")
    public String PayLoadController.delete(@PathVariable("id") Long id, @RequestParam(value = "page", required = false) Integer page, @RequestParam(value = "size", required = false) Integer size, Model uiModel) {
        PayLoad payLoad = PayLoad.findPayLoad(id);
        payLoad.remove();
        uiModel.asMap().clear();
        uiModel.addAttribute("page", (page == null) ? "1" : page.toString());
        uiModel.addAttribute("size", (size == null) ? "10" : size.toString());
        return "redirect:/payloads";
    }
    
    void PayLoadController.populateEditForm(Model uiModel, PayLoad payLoad) {
        uiModel.addAttribute("payLoad", payLoad);
        uiModel.addAttribute("msgelements", MsgElement.findAllMsgElements());
    }
    
    String PayLoadController.encodeUrlPathSegment(String pathSegment, HttpServletRequest httpServletRequest) {
        String enc = httpServletRequest.getCharacterEncoding();
        if (enc == null) {
            enc = WebUtils.DEFAULT_CHARACTER_ENCODING;
        }
        try {
            pathSegment = UriUtils.encodePathSegment(pathSegment, enc);
        } catch (UnsupportedEncodingException uee) {}
        return pathSegment;
    }
    
}
