// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.nasa.hackson.nasachatbot.domain;

import com.nasa.hackson.nasachatbot.domain.PayLoad;

privileged aspect PayLoad_Roo_JavaBean {
    
    public String PayLoad.getTemplateType() {
        return this.templateType;
    }
    
    public void PayLoad.setTemplateType(String templateType) {
        this.templateType = templateType;
    }
    
    public String PayLoad.getName() {
        return this.name;
    }
    
    public void PayLoad.setName(String name) {
        this.name = name;
    }
    
}
