// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.nasa.hackson.nasachatbot.domain;

import com.nasa.hackson.nasachatbot.domain.PayLoad;
import org.codehaus.jackson.annotate.JsonIgnore;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Version;

privileged aspect PayLoad_Roo_Jpa_Entity {
    
    declare @type: PayLoad: @Entity;
    
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "id")
    @JsonIgnore
    private Long PayLoad.id;

    @JsonIgnore
    @Version
    @Column(name = "version")
    private Integer PayLoad.version;
    
    public Long PayLoad.getId() {
        return this.id;
    }
    
    public void PayLoad.setId(Long id) {
        this.id = id;
    }
    
    public Integer PayLoad.getVersion() {
        return this.version;
    }
    
    public void PayLoad.setVersion(Integer version) {
        this.version = version;
    }
    
}
