// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.nasa.hackson.nasachatbot.domain;

import com.nasa.hackson.nasachatbot.domain.PayLoad;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect PayLoad_Roo_Configurable {
    
    declare @type: PayLoad: @Configurable;
    
}
